import requests
import xml.etree.ElementTree as Et
import json
import re
# tally-prime URL


class TallyPrimeIntegration:
    def __init__(self, url):
        self.url = url

    def fetch_ledger(self, ledger_xml_file='xml_flie/fetchledger.xml'):
        with open(ledger_xml_file, 'r') as f:
            ledger_data = f.read()
        ledger_request = requests.post(url=self.url, data=ledger_data)
        ledger_response = ledger_request.text.strip()
        responseXML = Et.fromstring(ledger_response)

        ledger_list = []
        for data in responseXML.findall('./BODY/DATA/COLLECTION/LEDGER'):
            dataOFledger = data.get('NAME')
            ledger_list.append(dataOFledger)

        return ledger_list

    def create_ledger(self, ledger_json_file):
        f = open(ledger_json_file)
        ledger_data = json.load(f)
        global led_name, led_gst, led_total, total_gst, led_invoice, sgst, cgst, total_gst1

        led_name = ledger_data['COMP_NAME']
        led_invoice = ledger_data['INVOICE_NO']
        led_group = 'Sundry Debtors'
        led_address = ledger_data['COMP_ADD']
        led_country = 'India'
        led_state = ledger_data['COMP_STATE']
        led_mobile = '9987546523'
        led_gst = ledger_data['COMP_GST']
        led_total = ledger_data['TOTAL']
        total_gst1 = re.sub('[^0-9. ]','',ledger_data['TAX_AMOUNT'])
        # print(total_gst1)
        total_gst = float(re.sub('[^0-9. ]','',ledger_data['TAX_AMOUNT']))/2
        sgst = total_gst
        cgst = total_gst

        ledger_list = self.fetch_ledger('xml_flie/fetchledger.xml')

        if led_name in ledger_list:
            print('Ledger already exists')
        else:
            data = '<ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER><BODY>'
            data += '<IMPORTDATA><REQUESTDESC><REPORTNAME>All Masters</REPORTNAME></REQUESTDESC><REQUESTDATA>'
            data += '<TALLYMESSAGE xmlns:UDF="TallyUDF"><LEDGER Action="Create"><NAME>' + \
                led_name+'</NAME><PARENT>'+led_group
            data += '</PARENT><ADDRESS>'+led_address + \
                '</ADDRESS><COUNTRYOFRESIDENCE>'+led_country+'</COUNTRYOFRESIDENCE>'
            data += '<LEDSTATENAME>'+led_state+'</LEDSTATENAME><LEDGERMOBILE>' + \
                led_mobile+'</LEDGERMOBILE><PARTYGSTIN>'
            data += led_gst+'</PARTYGSTIN></LEDGER></TALLYMESSAGE></REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>'
            # print(data)
            requests.post(url=self.url, data=data)

    def fetch_stockitem(self, stock_json_file):
        with open('xml_flie/stockitems_fetch.xml', 'r') as f:
            stock_data = f.read()

            stock_request = requests.post(url=url, data=stock_data)
            stock_response = stock_request.text.strip()
            responseXML = Et.fromstring(stock_response)

        stockitem_list = []
        for data in responseXML.findall('./BODY/DATA/COLLECTION/STOCKITEM'):
            # data1 = list(data.get('NAME'))
            dataOFstock = data.get('NAME')
            stockitem_list.append(dataOFstock)
        # print(color.GREEN, stockitem_list)

        f = open(stock_json_file)
        all_stock_data = json.load(f)
        # print(len(all_stock_data))
        for stock_data in all_stock_data:
            for key in stock_data.keys():
                if re.search('Description', key):
                    stock_desc = stock_data[key]
                    stock_qty = stock_data['Quantity']
                    if 'PC' in stock_data['Quantity']:
                        stock_data['Quantity'] = stock_data['Quantity'].replace("PC", "PCS")
                        
                    stock_rate = stock_data['Rate']
                    stock_amt = stock_data['Amount']
                    
                    stock_per = stock_data['per']
                    if 'PC' in stock_data['per']:
                        stock_data['per'] = stock_data['per'].replace("PC", "PCS")
                    

        if stock_desc in stockitem_list:
            print('Item already exists')
        else:
            for stock_data in all_stock_data:
                for key in stock_data.keys():
                    if re.search('Description', key):
                        stock_desc = stock_data[key]
                        stock_qty = stock_data['Quantity']
                        if 'PC' in stock_data['Quantity']:
                            stock_data['Quantity'] = stock_data['Quantity'].replace("PC", "PCS")

                        stock_rate = stock_data['Rate']
                        stock_amt = stock_data['Amount']

                        stock_per = stock_data['per']
                        if 'PC' in stock_data['per']:
                            stock_data['per'] = stock_data['per'].replace("PC", "PCS")
                        
                        # print(stock_per)
                        # print(stock_qty)
                        data = '<ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER><BODY>'
                        data += '<IMPORTDATA><REQUESTDESC><REPORTNAME>All Masters</REPORTNAME></REQUESTDESC><REQUESTDATA>'
                        data += '<TALLYMESSAGE xmlns:UDF="TallyUDF"><STOCKITEM Action="Create"><NAME>' + \
                            stock_desc+'</NAME>'
                        data += '<BASEUNITS>'+stock_per + \
                            '</BASEUNITS></STOCKITEM></TALLYMESSAGE></REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>'
                        # print(data)
                        requests.post(url=url, data=data)
        if re.search('24', led_gst):
            data = '<ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER><BODY>'
            data += '<IMPORTDATA><REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME><STATICVARIABLES><SVCURRENTCOMPANY>Samyak Instrumentation Pvt Ltd</SVCURRENTCOMPANY></STATICVARIABLES>'
            data += '</REQUESTDESC><REQUESTDATA><TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Purchase" ACTION="Create" OBJVIEW="Invoice Voucher View">'
            data += '<ADDRESS.LIST TYPE="String"><ADDRESS>None</ADDRESS></ADDRESS.LIST><BASICBUYERADDRESS.LIST TYPE="String"><BASICBUYERADDRESS>Memnagar</BASICBUYERADDRESS>'
            data += '</BASICBUYERADDRESS.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><DATE>20220401</DATE>'
            data += '<REFERENCEDATE>20220401</REFERENCEDATE><GUID>ec393735-c49b-42c2-83a4-9daceb111ab5-00000009</GUID><VATDEALERTYPE/><STATENAME>Gujarat</STATENAME><VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>'
            data += '<COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE><PARTYGSTIN>'+led_gst + \
                '</PARTYGSTIN><PLACEOFSUPPLY>Gujarat</PLACEOFSUPPLY><PARTYNAME>' + \
                    led_name+'</PARTYNAME><PARTYLEDGERNAME>'+led_name+'</PARTYLEDGERNAME>'
            data += '<REFERENCE>'+led_invoice+'</REFERENCE><PARTYMAILINGNAME>'+led_name + \
                '</PARTYMAILINGNAME><CONSIGNEEMAILINGNAME>Samyak Instrumentation Pvt Ltd</CONSIGNEEMAILINGNAME><CONSIGNEESTATENAME>Gujarat</CONSIGNEESTATENAME>'
            data += '<VOUCHERNUMBER>1</VOUCHERNUMBER><BASICBASEPARTYNAME>'+led_name + \
                '</BASICBASEPARTYNAME><CSTFORMISSUETYPE/><CSTFORMRECVTYPE/><FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE><PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>'
            data += '<BASICBUYERNAME>Samyak Instrumentation Pvt Ltd</BASICBUYERNAME><CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME><VCHGSTCLASS/><VCHENTRYMODE>Item Invoice</VCHENTRYMODE><DIFFACTUALQTY>No</DIFFACTUALQTY><ISMSTFROMSYNC>No</ISMSTFROMSYNC><ISDELETED>No</ISDELETED><ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED><ASORIGINAL>No</ASORIGINAL><AUDITED>No</AUDITED><FORJOBCOSTING>No</FORJOBCOSTING><ISOPTIONAL>No</ISOPTIONAL><EFFECTIVEDATE>20220401</EFFECTIVEDATE><USEFOREXCISE>No</USEFOREXCISE><ISFORJOBWORKIN>No</ISFORJOBWORKIN><ALLOWCONSUMPTION>No</ALLOWCONSUMPTION><USEFORINTEREST>No</USEFORINTEREST><USEFORGAINLOSS>No</USEFORGAINLOSS><USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER><USEFORCOMPOUND>No</USEFORCOMPOUND><USEFORSERVICETAX>No</USEFORSERVICETAX><ISONHOLD>No</ISONHOLD><ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE><ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE><ISEXCISEVOUCHER>No</ISEXCISEVOUCHER><EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE><USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER><IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION><EXCISEOPENING>No</EXCISEOPENING><USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION><ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN><ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN><ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH><INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH><ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT><ISVATOVERRIDDEN>No</ISVATOVERRIDDEN><IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE><ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS><ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS><ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN><ISISDVOUCHER>No</ISISDVOUCHER><ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN><ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH><ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN><GSTNOTEXPORTED>No</GSTNOTEXPORTED><IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION><ISGSTREFUND>No</ISGSTREFUND><OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY><ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT><IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION><IRNJSONEXPORTED>No</IRNJSONEXPORTED><IRNCANCELLED>No</IRNCANCELLED><ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE><ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS><ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY><ISCANCELLED>No</ISCANCELLED><HASCASHFLOW>No</HASCASHFLOW><ISPOSTDATED>No</ISPOSTDATED><USETRACKINGNUMBER>No</USETRACKINGNUMBER><ISINVOICE>Yes</ISINVOICE><MFGJOURNAL>No</MFGJOURNAL><HASDISCOUNTS>No</HASDISCOUNTS><ASPAYSLIP>No</ASPAYSLIP><ISCOSTCENTRE>No</ISCOSTCENTRE><ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH><ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON><ISBLANKCHEQUE>No</ISBLANKCHEQUE><ISVOID>No</ISVOID><ORDERLINESTATUS>No</ORDERLINESTATUS><VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES><VATISPURCEXEMPTED>No</VATISPURCEXEMPTED><ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE><VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH><ISVATDUTYPAID>Yes</ISVATDUTYPAID><ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE><ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR><ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED><CHANGEVCHMODE>No</CHANGEVCHMODE><RESETIRNQRCODE>No</RESETIRNQRCODE><ALTERID> 18</ALTERID><MASTERID> 9</MASTERID><VOUCHERKEY>191774584733704</VOUCHERKEY><EWAYBILLDETAILS.LIST></EWAYBILLDETAILS.LIST><EXCLUDEDTAXATIONS.LIST></EXCLUDEDTAXATIONS.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>'

            for stock_data in all_stock_data:
                for key in stock_data.keys():
                    if re.search('Description', key):
                        stock_desc = stock_data[key]
                        stock_qty = stock_data['Quantity']
                        if 'PC' in stock_data['Quantity']:
                            stock_data['Quantity'] = stock_data['Quantity'].replace("PC", "PCS")
                            
                        stock_per = stock_data['per']    
                        if 'PC' in stock_data['per']:
                            stock_data['per'] = stock_data['per'].replace("PC", "PCS")
                        stock_rate = stock_data['Rate']
                        stock_amt = stock_data['Amount']
                        # stock_per = stock_data['per']

                data += '<ALLINVENTORYENTRIES.LIST><STOCKITEMNAME>'+stock_desc + \
                    '</STOCKITEMNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>'
                data += '<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISAUTONEGATE>No</ISAUTONEGATE><ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE><ISTRACKCOMPONENT>No</ISTRACKCOMPONENT><ISTRACKPRODUCTION>No</ISTRACKPRODUCTION><ISPRIMARYITEM>No</ISPRIMARYITEM><ISSCRAP>No</ISSCRAP>'
                data += '<RATE>'+stock_rate+'</RATE><AMOUNT>'"-"+stock_amt+'</AMOUNT><ACTUALQTY> ' + stock_qty+'</ACTUALQTY><BILLEDQTY> '+stock_qty + \
                        '</BILLEDQTY><BATCHALLOCATIONS.LIST>'
                data += '<GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><INDENTNO/><ORDERNO/><TRACKINGNUMBER/><DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>'
                data += '<AMOUNT>'"-"+stock_amt+'</AMOUNT><ACTUALQTY> '+stock_qty+'</ACTUALQTY><BILLEDQTY> '+stock_qty + \
                    '</BILLEDQTY><ADDITIONALDETAILS.LIST></ADDITIONALDETAILS.LIST><VOUCHERCOMPONENTLIST.LIST></VOUCHERCOMPONENTLIST.LIST></BATCHALLOCATIONS.LIST><ACCOUNTINGALLOCATIONS.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>'
                data += '<LEDGERNAME>Purchase GST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
                data += '<AMOUNT>'"-"+stock_amt+'</AMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></ACCOUNTINGALLOCATIONS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><EXCISEALLOCATIONS.LIST></EXCISEALLOCATIONS.LIST><EXPENSEALLOCATIONS.LIST></EXPENSEALLOCATIONS.LIST></ALLINVENTORYENTRIES.LIST>'
            data += '<SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST><EWAYBILLERRORLIST.LIST></EWAYBILLERRORLIST.LIST><IRNERRORLIST.LIST></IRNERRORLIST.LIST><INVOICEDELNOTES.LIST></INVOICEDELNOTES.LIST><INVOICEORDERLIST.LIST></INVOICEORDERLIST.LIST><INVOICEINDENTLIST.LIST></INVOICEINDENTLIST.LIST><ATTENDANCEENTRIES.LIST></ATTENDANCEENTRIES.LIST><ORIGINVOICEDETAILS.LIST></ORIGINVOICEDETAILS.LIST><INVOICEEXPORTLIST.LIST></INVOICEEXPORTLIST.LIST><LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>'
            data += '<LEDGERNAME>'+led_name+'</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>Yes</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>'+led_total + \
                '</AMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST>'
            data += '<NAME>'+led_invoice+'</NAME><BILLTYPE>New Ref</BILLTYPE><TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE><AMOUNT>'+led_total+'</AMOUNT><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # this is for IGST
            # data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><LEDGERNAME>IGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            # data += '<AMOUNT>'"-"+total_gst1+'</AMOUNT><VATEXPAMOUNT>'"-"+total_gst1+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # this is for CGST and SGST
            data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><ROUNDTYPE/>'
            data += '<LEDGERNAME>CGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>'"-"+str(cgst)+'</AMOUNT><VATEXPAMOUNT>'"-"+str(cgst)+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><ROUNDTYPE/><LEDGERNAME>SGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>'"-"+str(sgst)+'</AMOUNT><VATEXPAMOUNT>'"-"+str(sgst)+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # till this CGST and SGST
            data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><LEDGERNAME>Freight Sales Gst</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>-350.00</AMOUNT><VATEXPAMOUNT>-350.00</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST><PAYROLLMODEOFPAYMENT.LIST></PAYROLLMODEOFPAYMENT.LIST><ATTDRECORDS.LIST></ATTDRECORDS.LIST><GSTEWAYCONSIGNORADDRESS.LIST></GSTEWAYCONSIGNORADDRESS.LIST><GSTEWAYCONSIGNEEADDRESS.LIST></GSTEWAYCONSIGNEEADDRESS.LIST><TEMPGSTRATEDETAILS.LIST></TEMPGSTRATEDETAILS.LIST></VOUCHER></TALLYMESSAGE></REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>'
            # print(data)
            requests.post(url=url, data=data)

        else:
            data = '<ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER><BODY>'
            data += '<IMPORTDATA><REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME><STATICVARIABLES><SVCURRENTCOMPANY>Samyak Instrumentation Pvt Ltd</SVCURRENTCOMPANY></STATICVARIABLES>'
            data += '</REQUESTDESC><REQUESTDATA><TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Purchase" ACTION="Create" OBJVIEW="Invoice Voucher View">'
            data += '<ADDRESS.LIST TYPE="String"><ADDRESS>None</ADDRESS></ADDRESS.LIST><BASICBUYERADDRESS.LIST TYPE="String"><BASICBUYERADDRESS>Memnagar</BASICBUYERADDRESS>'
            data += '</BASICBUYERADDRESS.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><DATE>20220401</DATE>'
            data += '<REFERENCEDATE>20220401</REFERENCEDATE><GUID>ec393735-c49b-42c2-83a4-9daceb111ab5-00000009</GUID><VATDEALERTYPE/><STATENAME>Gujarat</STATENAME><VOUCHERTYPENAME>Purchase</VOUCHERTYPENAME>'
            data += '<COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE><PARTYGSTIN>'+led_gst + \
                '</PARTYGSTIN><PLACEOFSUPPLY>Gujarat</PLACEOFSUPPLY><PARTYNAME>' + \
                    led_name+'</PARTYNAME><PARTYLEDGERNAME>'+led_name+'</PARTYLEDGERNAME>'
            data += '<REFERENCE>'+led_invoice+'</REFERENCE><PARTYMAILINGNAME>'+led_name + \
                '</PARTYMAILINGNAME><CONSIGNEEMAILINGNAME>Samyak Instrumentation Pvt Ltd</CONSIGNEEMAILINGNAME><CONSIGNEESTATENAME>Gujarat</CONSIGNEESTATENAME>'
            data += '<VOUCHERNUMBER>1</VOUCHERNUMBER><BASICBASEPARTYNAME>'+led_name + \
                '</BASICBASEPARTYNAME><CSTFORMISSUETYPE/><CSTFORMRECVTYPE/><FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE><PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>'
            data += '<BASICBUYERNAME>Samyak Instrumentation Pvt Ltd</BASICBUYERNAME><CONSIGNEECOUNTRYNAME>India</CONSIGNEECOUNTRYNAME><VCHGSTCLASS/><VCHENTRYMODE>Item Invoice</VCHENTRYMODE><DIFFACTUALQTY>No</DIFFACTUALQTY><ISMSTFROMSYNC>No</ISMSTFROMSYNC><ISDELETED>No</ISDELETED><ISSECURITYONWHENENTERED>No</ISSECURITYONWHENENTERED><ASORIGINAL>No</ASORIGINAL><AUDITED>No</AUDITED><FORJOBCOSTING>No</FORJOBCOSTING><ISOPTIONAL>No</ISOPTIONAL><EFFECTIVEDATE>20220401</EFFECTIVEDATE><USEFOREXCISE>No</USEFOREXCISE><ISFORJOBWORKIN>No</ISFORJOBWORKIN><ALLOWCONSUMPTION>No</ALLOWCONSUMPTION><USEFORINTEREST>No</USEFORINTEREST><USEFORGAINLOSS>No</USEFORGAINLOSS><USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER><USEFORCOMPOUND>No</USEFORCOMPOUND><USEFORSERVICETAX>No</USEFORSERVICETAX><ISONHOLD>No</ISONHOLD><ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE><ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE><ISEXCISEVOUCHER>No</ISEXCISEVOUCHER><EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE><USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER><IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION><EXCISEOPENING>No</EXCISEOPENING><USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION><ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN><ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN><ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH><INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH><ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT><ISVATOVERRIDDEN>No</ISVATOVERRIDDEN><IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE><ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS><ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS><ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN><ISISDVOUCHER>No</ISISDVOUCHER><ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN><ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH><ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN><GSTNOTEXPORTED>No</GSTNOTEXPORTED><IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION><ISGSTREFUND>No</ISGSTREFUND><OVRDNEWAYBILLAPPLICABILITY>No</OVRDNEWAYBILLAPPLICABILITY><ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT><IGNOREEINVVALIDATION>No</IGNOREEINVVALIDATION><IRNJSONEXPORTED>No</IRNJSONEXPORTED><IRNCANCELLED>No</IRNCANCELLED><ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE><ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS><ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY><ISCANCELLED>No</ISCANCELLED><HASCASHFLOW>No</HASCASHFLOW><ISPOSTDATED>No</ISPOSTDATED><USETRACKINGNUMBER>No</USETRACKINGNUMBER><ISINVOICE>Yes</ISINVOICE><MFGJOURNAL>No</MFGJOURNAL><HASDISCOUNTS>No</HASDISCOUNTS><ASPAYSLIP>No</ASPAYSLIP><ISCOSTCENTRE>No</ISCOSTCENTRE><ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH><ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON><ISBLANKCHEQUE>No</ISBLANKCHEQUE><ISVOID>No</ISVOID><ORDERLINESTATUS>No</ORDERLINESTATUS><VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES><VATISPURCEXEMPTED>No</VATISPURCEXEMPTED><ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE><VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH><ISVATDUTYPAID>Yes</ISVATDUTYPAID><ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE><ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR><ISDELETEDVCHRETAINED>No</ISDELETEDVCHRETAINED><CHANGEVCHMODE>No</CHANGEVCHMODE><RESETIRNQRCODE>No</RESETIRNQRCODE><ALTERID> 18</ALTERID><MASTERID> 9</MASTERID><VOUCHERKEY>191774584733704</VOUCHERKEY><EWAYBILLDETAILS.LIST></EWAYBILLDETAILS.LIST><EXCLUDEDTAXATIONS.LIST></EXCLUDEDTAXATIONS.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST>'

            for stock_data in all_stock_data:
                for key in stock_data.keys():
                    if re.search('Description', key):
                        stock_desc = stock_data[key]
                        stock_qty = stock_data['Quantity']
                        if 'PC' in stock_data['Quantity']:
                            stock_data['Quantity'] = stock_data['Quantity'].replace("PC", "PCS")
                            
                        stock_per = stock_data['per']    
                        if 'PC' in stock_data['per']:
                            stock_data['per'] = stock_data['per'].replace("PC", "PCS")
                        stock_rate = stock_data['Rate']
                        stock_amt = stock_data['Amount']
                        # stock_per = stock_data['per']

                data += '<ALLINVENTORYENTRIES.LIST><STOCKITEMNAME>'+stock_desc + \
                    '</STOCKITEMNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>'
                data += '<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISAUTONEGATE>No</ISAUTONEGATE><ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE><ISTRACKCOMPONENT>No</ISTRACKCOMPONENT><ISTRACKPRODUCTION>No</ISTRACKPRODUCTION><ISPRIMARYITEM>No</ISPRIMARYITEM><ISSCRAP>No</ISSCRAP>'
                data += '<RATE>'+stock_rate+'</RATE><AMOUNT>'"-"+stock_amt+'</AMOUNT><ACTUALQTY> ' + stock_qty+'</ACTUALQTY><BILLEDQTY> '+stock_qty + \
                        '</BILLEDQTY><BATCHALLOCATIONS.LIST>'
                data += '<GODOWNNAME>Main Location</GODOWNNAME><BATCHNAME>Primary Batch</BATCHNAME><INDENTNO/><ORDERNO/><TRACKINGNUMBER/><DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>'
                data += '<AMOUNT>'"-"+stock_amt+'</AMOUNT><ACTUALQTY> '+stock_qty+'</ACTUALQTY><BILLEDQTY> '+stock_qty + \
                    '</BILLEDQTY><ADDITIONALDETAILS.LIST></ADDITIONALDETAILS.LIST><VOUCHERCOMPONENTLIST.LIST></VOUCHERCOMPONENTLIST.LIST></BATCHALLOCATIONS.LIST><ACCOUNTINGALLOCATIONS.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>'
                data += '<LEDGERNAME>Purchase GST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
                data += '<AMOUNT>'"-"+stock_amt+'</AMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></ACCOUNTINGALLOCATIONS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><EXCISEALLOCATIONS.LIST></EXCISEALLOCATIONS.LIST><EXPENSEALLOCATIONS.LIST></EXPENSEALLOCATIONS.LIST></ALLINVENTORYENTRIES.LIST>'
            data += '<SUPPLEMENTARYDUTYHEADDETAILS.LIST></SUPPLEMENTARYDUTYHEADDETAILS.LIST><EWAYBILLERRORLIST.LIST></EWAYBILLERRORLIST.LIST><IRNERRORLIST.LIST></IRNERRORLIST.LIST><INVOICEDELNOTES.LIST></INVOICEDELNOTES.LIST><INVOICEORDERLIST.LIST></INVOICEORDERLIST.LIST><INVOICEINDENTLIST.LIST></INVOICEINDENTLIST.LIST><ATTENDANCEENTRIES.LIST></ATTENDANCEENTRIES.LIST><ORIGINVOICEDETAILS.LIST></ORIGINVOICEDETAILS.LIST><INVOICEEXPORTLIST.LIST></INVOICEEXPORTLIST.LIST><LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST>'
            data += '<LEDGERNAME>'+led_name+'</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>Yes</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>'+led_total + \
                '</AMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST>'
            data += '<NAME>'+led_invoice+'</NAME><BILLTYPE>New Ref</BILLTYPE><TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE><AMOUNT>'+led_total+'</AMOUNT><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><STBILLCATEGORIES.LIST></STBILLCATEGORIES.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # this is for IGST
            data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><LEDGERNAME>IGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>'"-"+total_gst1+'</AMOUNT><VATEXPAMOUNT>'"-"+total_gst1+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # this is for CGST and SGST
            # data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><ROUNDTYPE/>'
            # data += '<LEDGERNAME>CGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            # data += '<AMOUNT>'"-"+str(cgst)+'</AMOUNT><VATEXPAMOUNT>'"-"+str(cgst)+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><ROUNDTYPE/><LEDGERNAME>SGST</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            # data += '<AMOUNT>'"-"+str(sgst)+'</AMOUNT><VATEXPAMOUNT>'"-"+str(sgst)+'</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST>'
            # till this CGST and SGST
            data += '<LEDGERENTRIES.LIST><OLDAUDITENTRYIDS.LIST TYPE="Number"><OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS></OLDAUDITENTRYIDS.LIST><LEDGERNAME>Freight Sales Gst</LEDGERNAME><GSTCLASS/><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><LEDGERFROMITEM>No</LEDGERFROMITEM><REMOVEZEROENTRIES>No</REMOVEZEROENTRIES><ISPARTYLEDGER>No</ISPARTYLEDGER><ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE><ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED><ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>'
            data += '<AMOUNT>-455.00</AMOUNT><VATEXPAMOUNT>-455.00</VATEXPAMOUNT><SERVICETAXDETAILS.LIST></SERVICETAXDETAILS.LIST><BANKALLOCATIONS.LIST></BANKALLOCATIONS.LIST><BILLALLOCATIONS.LIST></BILLALLOCATIONS.LIST><INTERESTCOLLECTION.LIST></INTERESTCOLLECTION.LIST><OLDAUDITENTRIES.LIST></OLDAUDITENTRIES.LIST><ACCOUNTAUDITENTRIES.LIST></ACCOUNTAUDITENTRIES.LIST><AUDITENTRIES.LIST></AUDITENTRIES.LIST><INPUTCRALLOCS.LIST></INPUTCRALLOCS.LIST><DUTYHEADDETAILS.LIST></DUTYHEADDETAILS.LIST><EXCISEDUTYHEADDETAILS.LIST></EXCISEDUTYHEADDETAILS.LIST><RATEDETAILS.LIST></RATEDETAILS.LIST><SUMMARYALLOCS.LIST></SUMMARYALLOCS.LIST><STPYMTDETAILS.LIST></STPYMTDETAILS.LIST><EXCISEPAYMENTALLOCATIONS.LIST></EXCISEPAYMENTALLOCATIONS.LIST><TAXBILLALLOCATIONS.LIST></TAXBILLALLOCATIONS.LIST><TAXOBJECTALLOCATIONS.LIST></TAXOBJECTALLOCATIONS.LIST><TDSEXPENSEALLOCATIONS.LIST></TDSEXPENSEALLOCATIONS.LIST><VATSTATUTORYDETAILS.LIST></VATSTATUTORYDETAILS.LIST><COSTTRACKALLOCATIONS.LIST></COSTTRACKALLOCATIONS.LIST><REFVOUCHERDETAILS.LIST></REFVOUCHERDETAILS.LIST><INVOICEWISEDETAILS.LIST></INVOICEWISEDETAILS.LIST><VATITCDETAILS.LIST></VATITCDETAILS.LIST><ADVANCETAXDETAILS.LIST></ADVANCETAXDETAILS.LIST></LEDGERENTRIES.LIST><PAYROLLMODEOFPAYMENT.LIST></PAYROLLMODEOFPAYMENT.LIST><ATTDRECORDS.LIST></ATTDRECORDS.LIST><GSTEWAYCONSIGNORADDRESS.LIST></GSTEWAYCONSIGNORADDRESS.LIST><GSTEWAYCONSIGNEEADDRESS.LIST></GSTEWAYCONSIGNEEADDRESS.LIST><TEMPGSTRATEDETAILS.LIST></TEMPGSTRATEDETAILS.LIST></VOUCHER></TALLYMESSAGE></REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>'
            # print(data)
            requests.post(url=url, data=data)

url = "http://localhost:9000"
# x = TallyPrimeIntegration(url)
# x.create_ledger('json_file/14970.json')
# x.fetch_stockitem('json_file/14970_table.json')
