apiVersion: v1
kind: Service
metadata:
  name: tally-app
spec:
  selector:
    app: tally-app
  ports:
    - protocol: "TCP"
      port: 7000
      targetPort: 5006
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tally-app
spec:
  selector:
    matchLabels:
      app: tally-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tally-app
    spec:
      containers:
        - name: tally-app
          image: tally_ocr:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5006
