apiVersion: v1
kind: Service
metadata:
  name: table-app
spec:
  selector:
    app: tabular-app
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 2120
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: table-app
spec:
  selector:
    matchLabels:
      app: tabular-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tabular-app
    spec:
      containers:
        - name: table-app
          image: table_image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2120
